In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

In [3]:
# list , array
lst = [1,2,3,4,5,5,6,6]
arr= np.array(lst)


In [4]:
arr

array([1, 2, 3, 4, 5, 5, 6, 6])

In [5]:
np.array([1,2,3,4,5,5,6,6,7,8,9])


array([1, 2, 3, 4, 5, 5, 6, 6, 7, 8, 9])

In [6]:
arr

array([1, 2, 3, 4, 5, 5, 6, 6])

In [7]:
lst=[1,2,3,4,5,6,7,7]
print("type of list",type(lst))
arr=np.array(lst)
print(arr)
print("type of array",type(arr))



type of list <class 'list'>
[1 2 3 4 5 6 7 7]
type of array <class 'numpy.ndarray'>


In [8]:
arr=np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
arr =np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((5,10))   ###5 row and 10 column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
# 1d array convert array into 2d arrray
arr =np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [20]:
arr =np.random.randint(1,5,9) 
arr

array([1, 2, 1, 4, 4, 3, 1, 3, 1], dtype=int32)

In [21]:
arr =np.random.randint(1,5,(3,3)) 
arr

array([[1, 2, 3],
       [3, 1, 1],
       [3, 4, 2]], dtype=int32)

In [22]:
arr =np.random.random(10)
arr

array([0.80228769, 0.78886907, 0.56626891, 0.13801407, 0.63371752,
       0.40846482, 0.93352503, 0.81311386, 0.30405208, 0.87567841])

In [23]:
arr=np.random.random((5,10))
arr

array([[0.67602423, 0.98225471, 0.18768598, 0.02871607, 0.76915505,
        0.39436818, 0.76169267, 0.62015405, 0.04858942, 0.35918956],
       [0.83084179, 0.81564404, 0.87969187, 0.51669645, 0.2079209 ,
        0.61261955, 0.95603329, 0.83361205, 0.90607043, 0.74856575],
       [0.58049544, 0.10262359, 0.13244677, 0.47174048, 0.63554229,
        0.73659601, 0.26539266, 0.67971722, 0.04867253, 0.71848297],
       [0.16653058, 0.3055079 , 0.38858505, 0.6919559 , 0.02618635,
        0.92677775, 0.7075431 , 0.37405512, 0.42614386, 0.91417836],
       [0.83063531, 0.56125182, 0.92449395, 0.30899657, 0.64999436,
        0.37154727, 0.97710411, 0.8527181 , 0.40997999, 0.75375696]])

In [24]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [25]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print("data type:-",arr.dtype)
print("number of dimension",arr.ndim)


shape of array (12, 5)
size of array 60
data type:- int64
number of dimension 2


In [26]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
arr.flatten()  ## home work (differeence)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [28]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [29]:
arr.shape

(12, 5)

In [30]:
arr.T.shape

(5, 12)

In [31]:
arr =np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
arr[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr[0]=100

In [35]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [36]:
np.arange(60).reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [37]:
print("shape of array:",arr.shape)
print("size of arrray:",arr.size)
print("data type of array:",arr.dtype)
print("number of dimension:",arr.ndim)

shape of array: (30,)
size of arrray: 30
data type of array: int64
number of dimension: 1


In [38]:
arr.flatten()

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [39]:
arr.ravel()

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [40]:
arr.shape

(30,)

In [41]:
arr.T.shape

(30,)

In [42]:
arr = np.arange(30)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
arr = np.arange(60).reshape(12,5) 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [45]:
arr[1,3:5]

array([8, 9])

In [46]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [47]:
arr[1,1] = 100

In [48]:
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [49]:
arr[11,4]

np.int64(59)

In [50]:
arr[-1,-1]

np.int64(59)

In [51]:
arr[11][-1]

np.int64(59)

In [52]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [53]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [54]:
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [55]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [56]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [57]:
arr[0,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [58]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [59]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [60]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [61]:
arr[:,0:1,0:1]


array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [62]:
arr[0,1,1] = 1000

In [63]:
arr[0,1,1]

np.int64(1000)

In [64]:
arr =np.array((1,5,6,9,2,3))

In [65]:
arr.sort()

In [66]:
arr

array([1, 2, 3, 5, 6, 9])

In [67]:
arr+2

array([ 3,  4,  5,  7,  8, 11])

In [68]:
arr*2

array([ 2,  4,  6, 10, 12, 18])

In [69]:
arr/2

array([0.5, 1. , 1.5, 2.5, 3. , 4.5])

In [70]:
arr-2

array([-1,  0,  1,  3,  4,  7])

In [71]:

arr1= np.array([1,2,3,5])
arr2 = np.array([1,6,3,5])

In [72]:
###arr1+arr2
##arr1*arr
arr1-arr2

array([ 0, -4,  0,  0])